# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'RxAndCS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxAndCS
    pod 'RxSwift', '~> 5.0'
    pod 'RxCocoa', '~> 5.0'
    pod 'RxAlamofire'
end

