# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'WA_CleanSwift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WA_CleanSwift
    pod 'RxSwift' 
    pod 'RxCocoa'
    pod 'RxAlamofire'
end

